### ISSUE TITLE
Arduino_Sensorkit.h not found error in Arduino_SensorKit.cpp -> fix to Arduino_SensorKit.h

### ISSUE THREAD

**Issue by noppatoppa** [arduino-libraries/Arduino_SensorKit#2]
There seems to be a small problem with the library. Don't know if you accept pull requests, but here's a description:

Compiling fails on Arduino IDE. Error indicates:
`Alternatives for Arduino_Sensorkit.h: []/home/jaska/Work/arduino/libraries/Arduino_Sensorkit/src/Arduino_SensorKit.cpp:1:10: fatal error: Arduino_Sensorkit.h: No such file or directory`

Looked at Arduino_SensorKit.cpp. Line 1 is:
`#include "Arduino_Sensorkit.h"`
The header file it's looking for is
`Arduino_SensorKit.h`

Suggest change of Arduino_SensorKit.cpp to:
`#include "Arduino_SensorKit.h"`

Line in question:
https://github.com/arduino-libraries/Arduino_SensorKit/blob/239e4335b9731b24cbc28d8c3ddd6cc7a0b0e7e7/src/Arduino_SensorKit.cpp#L1

Library version: 1.0.4

**Comment by marqdevx** [comment]
Fixed, thanks!!
