### ISSUE TITLE
Oled display stay black if Acceleration or Pressure module is added

### ISSUE THREAD

**Issue by ArduiDid** [arduino-libraries/Arduino_SensorKit#24]
Hello guys,

  I recently bought a Sensor Kit then added an Arduino Uno Rev 3 on it. I use IDE 1.8.3 or 1.8.16 on W10 PC. I try "Combined_Demo.ino" which sounds very promising to me because I was looking for a tool to check all sensors.
  
  All sensors are running well when I tested them individually. Also all other sensors are working well with the Oled display but not Acceleration **or** Pressure sensors. The issue append even with no command related to these sensors but just Accelerometer.begin(); or Pressure.begin(); function mentioned in the setup() function. The display stay black if I uncomment any of these two functions.
  
  I try Oled.setBusClock(100000); before Oled.begin(); to change bus speed with no success. Let me know if I can try something else.
  
 Thank in advance for your help
 Didier
 Note : *This is my first post in GitHub, please excuse me if it was not the right place to write this. Nobody else can help neither the vendor nor Arduino forum.*

**Comment by marqdevx** [comment]
Hey! @ArduiDid This is the right place! Thanks for your feedback, we are aware about the issues and we are investigating them.

For some users switching back to version `1.0.8` works.

Please switch to that version, and it would be nice if you can include in this post the board you are using.
Thank you so much, have a nice one!

**Comment by ArduiDid** [comment]
Great it works with version 1.0.8 Thank you! 
I used Arduino Uno Rev 3 as I said in my post. I added here more details if it could help. Let me know if you need more details for debugging. I will be happy to help.

![image](https://user-images.githubusercontent.com/92545308/138086477-8051ac05-3aa2-43cd-a9b3-34ca6b3020f3.png)

**Comment by alranel** [comment]
This is fixed as of 1.4.0.
