### ISSUE TITLE
Examples/Oled_Display.ino: Screen upside down on base in example

### ISSUE THREAD

**Issue by noppatoppa** [arduino-libraries/Arduino_SensorKit#3]
Don't know if you accept pull requests to the examples, but in the Oled_Display.ino example the screen is upside down in relation to the base.

Suggest adding the following to setup function:
` void setup() {
   Oled.begin();
   Oled.setFlipMode(true); // Flip the screen orientation 180 degrees
 } `

The function in reference documentation: https://github.com/olikraus/u8g2/wiki/u8x8reference#setflipmode

Function in question
https://github.com/arduino-libraries/Arduino_SensorKit/blob/239e4335b9731b24cbc28d8c3ddd6cc7a0b0e7e7/examples/Oled_Display/Oled_Display.ino#L3-L5

Library version 1.0.4

**Comment by marqdevx** [comment]
Added, thanks!
