### ISSUE TITLE
OLED not working on 1.0.10

### ISSUE THREAD

**Issue by jensjeflensje** [arduino-libraries/Arduino_SensorKit#39]
When working with an Arduino UNO R4 WiFi, I noticed that the OLED screen was not working on library version 1.0.10.

My code:
```cpp
#define U8x8_DO_NOT_SET_WIRE_CLOCK

#include "Arduino_SensorKit.h"
 
void setup() {
  Serial.begin(9600);
  Oled.begin();
  Oled.setFlipMode(true);
}
 
void loop() {
  Oled.setFont(u8x8_font_chroma48medium8_r); 
  Oled.setCursor(0, 33);
  Oled.print("test");   
  Oled.refreshDisplay();
  Serial.println("test");
  delay(2000);
}
```

This code does print `test` in the serial console, meaning the end of the loop is actually reached. It doesn't show it on the screen though.

I read #21 and I tried the things they said there, but that didn't help.

The reason that I want to use version 1.0.10 and not downgrade to 1.0.8, is that I need version 1.0.10 for my temperature sensor: https://support.arduino.cc/hc/en-us/articles/5211864112924-Arduino-Sensor-Kit-s-DHT20-sensor-reading

Any ideas?

**Comment by alranel** [comment]
This is fixed as of 1.4.0. All sensors are expected to work on UNO R4 WiFi now!
