### ISSUE TITLE
Examples using I2C should explain that all I2C devices on the board conflict

### ISSUE THREAD

**Issue by marcmerlin** [arduino-libraries/Arduino_SensorKit#9]
Unfortunately they were not configured to use different addresses (although it seems possible with small solder points).
An obvious use of the kit is to read pressure or some other I2c value (like accelerometer), but that's not possible since they share I2C and conflict with the OLED. If you turn them on, the OLED stops working.
Not obvious at all for a beginner, documentation is needed.

**Comment by marqdevx** [comment]
Hey!
We are using u8x8 to save memory, if we use u8g2 we use more than 80% of the memory.

This kit is meant to use it with the content so maki the things simple was te main goal, but you are right that it has some graphic limitations, noted.

I will add some examples using the u8g2 library for advanced users that want to try more capabilities of the Hardware , thanks a lot for your feedback!!

Have a nice one.

**Comment by per1234** [comment]
@marqdevx I believe your reply was intended to be posted to the other issue: https://github.com/arduino-libraries/Arduino_SensorKit/issues/8

Since this issue has not been addressed, I'll reopen.

**Comment by marcmerlin** [comment]
(Sorry, I replied on the wrong bug too, I moved that comment to the other bug)

**Comment by marcmerlin** [comment]
I tried to give a better combined example that exercises most sensors, but wasn't able to combined them all due to this problem. The partial example is here
https://github.com/arduino-libraries/Arduino_SensorKit/pull/6

I'm pretty sure I can make it work by soldering address points on the sensors, but then I'd have code that only works on my board, so it's not useful as an example to your users.

**Comment by marqdevx** [comment]
> 
> 
> @marqdevx I believe your reply was intended to be posted to the other issue: #8
> 
> Since this issue has not been addressed, I'll reopen.

Oops, my fault!

**Comment by marqdevx** [comment]
Hey @marcmerlin
Could you please run the i2c scanner individually for each sensor? and give me your i2c addresses.

I can run both at the same time.

**Comment by marcmerlin** [comment]
My bad, you are correct.
```
I2C device found at address 0x19  !
I2C device found at address 0x3C  !
I2C device found at address 0x77  !
```

Now I need to find out why initializing 
//Accelerometer.begin();
or
 //Pressure.begin();

stops the OLED from working.
It's been a while since I've worked with I2C, do the drivers auto-scan all addresses to find the right device, and maybe send wrong init messages to the OLED that mess it up?

**Comment by marcmerlin** [comment]
For what it's worth, running the I2C scanner first, also stops the OLED from working, but that might be a different issue.
Either way, it'd be great to have a generic example, like the one I submitted, that exercises everything, proves that it all works, and helps a novice user running all of them correctly?

**Comment by marqdevx** [comment]
I'll add an example
thanks for the feedback!! @marcmerlin

**Comment by noppatoppa** [comment]
> An obvious use of the kit is to read pressure or some other I2c value (like accelerometer), but that's not possible since they share I2C and conflict with the OLED. If you turn them on, the OLED stops working.

Can confirm this: using air pressure sensor disables OLED.
Tested both with Arduino IDE and Web Editor with newest library versions.

**Comment by marqdevx** [comment]
Hello @marcmerlin @noppatoppa 
First, thanks for the feedback
And second, could you please test this branch and let me know if now its working fine?
https://github.com/arduino-libraries/Arduino_SensorKit/tree/display_hw_i2c

I think it has been some update in the display library, cause the SW I2C for the display was fixing an issue that we had, but now the issue came back, and switching back to the HW I2C seems to fix it.

Let me know
Have a good one! :D

**Comment by marcmerlin** [comment]
I can confirm, this works, thank you.
I sent you a PR of your own code :)  https://github.com/arduino-libraries/Arduino_SensorKit/pull/13
And if you don't mind, I'd be honored if you included my full example that uses all the sensors on the board
https://github.com/arduino-libraries/Arduino_SensorKit/pull/6

![PXL_20210112_234145790](https://user-images.githubusercontent.com/1369412/104388235-a9f01d00-54ed-11eb-8ef0-8609ed324a01.jpg)

**Comment by marqdevx** [comment]
I will have a look, I will talk in the Pull Request
